//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/GameInputControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputControl"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""b97aebbc-893d-4449-8b6b-55aac6bfc5c3"",
            ""actions"": [
                {
                    ""name"": ""moveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4df0a62f-fb68-4db4-94ea-a7009eb6791d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveRight"",
                    ""type"": ""Button"",
                    ""id"": ""fe276b9d-1348-40d7-bd08-23454fa44fa7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""b990b556-9469-499f-8dad-ce1f295bd625"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballCastByKeyboard"",
                    ""type"": ""Button"",
                    ""id"": ""e11ad96e-6c3e-4251-836b-250952a6fa6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballCastByMouse"",
                    ""type"": ""Button"",
                    ""id"": ""80ccb7d4-664e-4c5b-8f59-3c06a2fa71fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballDirUp"",
                    ""type"": ""Button"",
                    ""id"": ""5dada47b-9b94-499d-bd83-2e7814371956"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballDirDown"",
                    ""type"": ""Button"",
                    ""id"": ""abad3f76-24d4-4274-acda-6289fcbf8cb2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballDirLeft"",
                    ""type"": ""Button"",
                    ""id"": ""a597d130-bbe3-4206-9a1c-c1af92053a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballDirRight"",
                    ""type"": ""Button"",
                    ""id"": ""b02c06ad-f5b3-47ae-8bfa-5341059ba540"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Legacy"",
                    ""type"": ""Button"",
                    ""id"": ""97bfc33b-b7a4-4768-b489-0901470415e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireballDir"",
                    ""type"": ""Value"",
                    ""id"": ""a78df41a-d63a-45d6-8494-d0225a3d667b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""move"",
                    ""type"": ""Button"",
                    ""id"": ""5c8ee00f-f1f3-4862-b0c5-f44a3dbc1571"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9087f24d-4376-4d0c-97d2-2fa1840c92c9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballCastByMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bd37afd-61ab-4887-a01b-0f80f5c1a119"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballCastByKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be4fd5fb-15f5-4ba8-b962-82fe46d1f49b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballCastByKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""580c986d-293d-49d5-952d-f9d734cc8fb0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballCastByKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d36aaad0-b2b6-4a2a-aa81-fd8702b10211"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballCastByKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84471e13-9359-427a-9fff-8e46d00f2cd9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDirUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fd12355-eec3-47a9-b419-9030082c49b3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDirDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""023f6725-a0fc-4150-93b4-e1dd1a7024bb"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDirLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20d85193-6a00-453d-9e20-7a80b80ee068"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDirRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b382644f-9873-4508-8f91-020e79a9e284"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6d129271-7eff-4a27-9355-630ead53008d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9efa5ef9-5b42-469f-9ae0-b59ab000f4d3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3bdf3f58-046b-46c1-acf7-fd75951f7113"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d2677262-f8b5-4664-b108-8ce78a89beda"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""634518b8-d37a-4beb-aaea-fd89e689c79a"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3694a7da-9431-4fa7-9b55-0c3ade2af9cf"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Legacy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8d8b27e0-4317-44b0-8ba4-8a5d26a63d90"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDir"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1f65fad3-b566-4442-b144-e36b4da11587"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d3265530-a968-4455-9e83-d3b5c115e325"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aadadf33-bdfc-48be-b61f-277ee37c6813"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f78a1437-c013-42e0-87be-a12fb41fef0c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireballDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ed339f67-e110-4531-8401-758a51b93d65"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6728af4c-a6b6-41c5-90ae-d639fb2bdfa0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4048b58b-b92f-4767-ae04-9423013386f2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e5ba8b5-6768-4fad-8cb9-aa7cebd6c5c4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f76fa78-9236-4d63-b1e9-67f63103ba25"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51834b9e-8ce5-40ab-a319-12c6eb73678a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UINavigation"",
            ""id"": ""20a322a6-a5e7-45da-833a-ca2f321dfb1c"",
            ""actions"": [
                {
                    ""name"": ""nextSelection"",
                    ""type"": ""Button"",
                    ""id"": ""174dda5b-8eb3-4521-8131-a3f15349ada4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""previousSelection"",
                    ""type"": ""Button"",
                    ""id"": ""03757ac9-23ac-47d7-a5db-c4b688e53ace"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""confirm"",
                    ""type"": ""Button"",
                    ""id"": ""e13c8789-caff-438a-abb0-4a4587ca30c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""exit"",
                    ""type"": ""Button"",
                    ""id"": ""931fadb8-7b70-4779-9469-96c4ad6b56e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba6bac28-de5b-48e8-9c05-94c0af02656e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""nextSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7a69b21-7c6a-4408-8413-e190ad4fe35c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""previousSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5885e722-a957-48ba-a0c9-24fc16267ae4"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35d65490-c319-4e2c-9df1-7875e2e38bd6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Pause"",
            ""id"": ""51b03cda-71ed-45f7-acc4-2f88bf245da1"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""dcb97ea0-e929-4b95-ae49-498f0318e6c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""97231d84-1731-4e59-93cb-0676b2647e86"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_moveLeft = m_Player.FindAction("moveLeft", throwIfNotFound: true);
        m_Player_moveRight = m_Player.FindAction("moveRight", throwIfNotFound: true);
        m_Player_jump = m_Player.FindAction("jump", throwIfNotFound: true);
        m_Player_fireballCastByKeyboard = m_Player.FindAction("fireballCastByKeyboard", throwIfNotFound: true);
        m_Player_fireballCastByMouse = m_Player.FindAction("fireballCastByMouse", throwIfNotFound: true);
        m_Player_fireballDirUp = m_Player.FindAction("fireballDirUp", throwIfNotFound: true);
        m_Player_fireballDirDown = m_Player.FindAction("fireballDirDown", throwIfNotFound: true);
        m_Player_fireballDirLeft = m_Player.FindAction("fireballDirLeft", throwIfNotFound: true);
        m_Player_fireballDirRight = m_Player.FindAction("fireballDirRight", throwIfNotFound: true);
        m_Player_Legacy = m_Player.FindAction("Legacy", throwIfNotFound: true);
        m_Player_fireballDir = m_Player.FindAction("fireballDir", throwIfNotFound: true);
        m_Player_move = m_Player.FindAction("move", throwIfNotFound: true);
        // UINavigation
        m_UINavigation = asset.FindActionMap("UINavigation", throwIfNotFound: true);
        m_UINavigation_nextSelection = m_UINavigation.FindAction("nextSelection", throwIfNotFound: true);
        m_UINavigation_previousSelection = m_UINavigation.FindAction("previousSelection", throwIfNotFound: true);
        m_UINavigation_confirm = m_UINavigation.FindAction("confirm", throwIfNotFound: true);
        m_UINavigation_exit = m_UINavigation.FindAction("exit", throwIfNotFound: true);
        // Pause
        m_Pause = asset.FindActionMap("Pause", throwIfNotFound: true);
        m_Pause_Newaction = m_Pause.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_moveLeft;
    private readonly InputAction m_Player_moveRight;
    private readonly InputAction m_Player_jump;
    private readonly InputAction m_Player_fireballCastByKeyboard;
    private readonly InputAction m_Player_fireballCastByMouse;
    private readonly InputAction m_Player_fireballDirUp;
    private readonly InputAction m_Player_fireballDirDown;
    private readonly InputAction m_Player_fireballDirLeft;
    private readonly InputAction m_Player_fireballDirRight;
    private readonly InputAction m_Player_Legacy;
    private readonly InputAction m_Player_fireballDir;
    private readonly InputAction m_Player_move;
    public struct PlayerActions
    {
        private @GameInputControl m_Wrapper;
        public PlayerActions(@GameInputControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @moveLeft => m_Wrapper.m_Player_moveLeft;
        public InputAction @moveRight => m_Wrapper.m_Player_moveRight;
        public InputAction @jump => m_Wrapper.m_Player_jump;
        public InputAction @fireballCastByKeyboard => m_Wrapper.m_Player_fireballCastByKeyboard;
        public InputAction @fireballCastByMouse => m_Wrapper.m_Player_fireballCastByMouse;
        public InputAction @fireballDirUp => m_Wrapper.m_Player_fireballDirUp;
        public InputAction @fireballDirDown => m_Wrapper.m_Player_fireballDirDown;
        public InputAction @fireballDirLeft => m_Wrapper.m_Player_fireballDirLeft;
        public InputAction @fireballDirRight => m_Wrapper.m_Player_fireballDirRight;
        public InputAction @Legacy => m_Wrapper.m_Player_Legacy;
        public InputAction @fireballDir => m_Wrapper.m_Player_fireballDir;
        public InputAction @move => m_Wrapper.m_Player_move;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @moveLeft.started += instance.OnMoveLeft;
            @moveLeft.performed += instance.OnMoveLeft;
            @moveLeft.canceled += instance.OnMoveLeft;
            @moveRight.started += instance.OnMoveRight;
            @moveRight.performed += instance.OnMoveRight;
            @moveRight.canceled += instance.OnMoveRight;
            @jump.started += instance.OnJump;
            @jump.performed += instance.OnJump;
            @jump.canceled += instance.OnJump;
            @fireballCastByKeyboard.started += instance.OnFireballCastByKeyboard;
            @fireballCastByKeyboard.performed += instance.OnFireballCastByKeyboard;
            @fireballCastByKeyboard.canceled += instance.OnFireballCastByKeyboard;
            @fireballCastByMouse.started += instance.OnFireballCastByMouse;
            @fireballCastByMouse.performed += instance.OnFireballCastByMouse;
            @fireballCastByMouse.canceled += instance.OnFireballCastByMouse;
            @fireballDirUp.started += instance.OnFireballDirUp;
            @fireballDirUp.performed += instance.OnFireballDirUp;
            @fireballDirUp.canceled += instance.OnFireballDirUp;
            @fireballDirDown.started += instance.OnFireballDirDown;
            @fireballDirDown.performed += instance.OnFireballDirDown;
            @fireballDirDown.canceled += instance.OnFireballDirDown;
            @fireballDirLeft.started += instance.OnFireballDirLeft;
            @fireballDirLeft.performed += instance.OnFireballDirLeft;
            @fireballDirLeft.canceled += instance.OnFireballDirLeft;
            @fireballDirRight.started += instance.OnFireballDirRight;
            @fireballDirRight.performed += instance.OnFireballDirRight;
            @fireballDirRight.canceled += instance.OnFireballDirRight;
            @Legacy.started += instance.OnLegacy;
            @Legacy.performed += instance.OnLegacy;
            @Legacy.canceled += instance.OnLegacy;
            @fireballDir.started += instance.OnFireballDir;
            @fireballDir.performed += instance.OnFireballDir;
            @fireballDir.canceled += instance.OnFireballDir;
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @moveLeft.started -= instance.OnMoveLeft;
            @moveLeft.performed -= instance.OnMoveLeft;
            @moveLeft.canceled -= instance.OnMoveLeft;
            @moveRight.started -= instance.OnMoveRight;
            @moveRight.performed -= instance.OnMoveRight;
            @moveRight.canceled -= instance.OnMoveRight;
            @jump.started -= instance.OnJump;
            @jump.performed -= instance.OnJump;
            @jump.canceled -= instance.OnJump;
            @fireballCastByKeyboard.started -= instance.OnFireballCastByKeyboard;
            @fireballCastByKeyboard.performed -= instance.OnFireballCastByKeyboard;
            @fireballCastByKeyboard.canceled -= instance.OnFireballCastByKeyboard;
            @fireballCastByMouse.started -= instance.OnFireballCastByMouse;
            @fireballCastByMouse.performed -= instance.OnFireballCastByMouse;
            @fireballCastByMouse.canceled -= instance.OnFireballCastByMouse;
            @fireballDirUp.started -= instance.OnFireballDirUp;
            @fireballDirUp.performed -= instance.OnFireballDirUp;
            @fireballDirUp.canceled -= instance.OnFireballDirUp;
            @fireballDirDown.started -= instance.OnFireballDirDown;
            @fireballDirDown.performed -= instance.OnFireballDirDown;
            @fireballDirDown.canceled -= instance.OnFireballDirDown;
            @fireballDirLeft.started -= instance.OnFireballDirLeft;
            @fireballDirLeft.performed -= instance.OnFireballDirLeft;
            @fireballDirLeft.canceled -= instance.OnFireballDirLeft;
            @fireballDirRight.started -= instance.OnFireballDirRight;
            @fireballDirRight.performed -= instance.OnFireballDirRight;
            @fireballDirRight.canceled -= instance.OnFireballDirRight;
            @Legacy.started -= instance.OnLegacy;
            @Legacy.performed -= instance.OnLegacy;
            @Legacy.canceled -= instance.OnLegacy;
            @fireballDir.started -= instance.OnFireballDir;
            @fireballDir.performed -= instance.OnFireballDir;
            @fireballDir.canceled -= instance.OnFireballDir;
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UINavigation
    private readonly InputActionMap m_UINavigation;
    private List<IUINavigationActions> m_UINavigationActionsCallbackInterfaces = new List<IUINavigationActions>();
    private readonly InputAction m_UINavigation_nextSelection;
    private readonly InputAction m_UINavigation_previousSelection;
    private readonly InputAction m_UINavigation_confirm;
    private readonly InputAction m_UINavigation_exit;
    public struct UINavigationActions
    {
        private @GameInputControl m_Wrapper;
        public UINavigationActions(@GameInputControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @nextSelection => m_Wrapper.m_UINavigation_nextSelection;
        public InputAction @previousSelection => m_Wrapper.m_UINavigation_previousSelection;
        public InputAction @confirm => m_Wrapper.m_UINavigation_confirm;
        public InputAction @exit => m_Wrapper.m_UINavigation_exit;
        public InputActionMap Get() { return m_Wrapper.m_UINavigation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UINavigationActions set) { return set.Get(); }
        public void AddCallbacks(IUINavigationActions instance)
        {
            if (instance == null || m_Wrapper.m_UINavigationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UINavigationActionsCallbackInterfaces.Add(instance);
            @nextSelection.started += instance.OnNextSelection;
            @nextSelection.performed += instance.OnNextSelection;
            @nextSelection.canceled += instance.OnNextSelection;
            @previousSelection.started += instance.OnPreviousSelection;
            @previousSelection.performed += instance.OnPreviousSelection;
            @previousSelection.canceled += instance.OnPreviousSelection;
            @confirm.started += instance.OnConfirm;
            @confirm.performed += instance.OnConfirm;
            @confirm.canceled += instance.OnConfirm;
            @exit.started += instance.OnExit;
            @exit.performed += instance.OnExit;
            @exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(IUINavigationActions instance)
        {
            @nextSelection.started -= instance.OnNextSelection;
            @nextSelection.performed -= instance.OnNextSelection;
            @nextSelection.canceled -= instance.OnNextSelection;
            @previousSelection.started -= instance.OnPreviousSelection;
            @previousSelection.performed -= instance.OnPreviousSelection;
            @previousSelection.canceled -= instance.OnPreviousSelection;
            @confirm.started -= instance.OnConfirm;
            @confirm.performed -= instance.OnConfirm;
            @confirm.canceled -= instance.OnConfirm;
            @exit.started -= instance.OnExit;
            @exit.performed -= instance.OnExit;
            @exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(IUINavigationActions instance)
        {
            if (m_Wrapper.m_UINavigationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUINavigationActions instance)
        {
            foreach (var item in m_Wrapper.m_UINavigationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UINavigationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UINavigationActions @UINavigation => new UINavigationActions(this);

    // Pause
    private readonly InputActionMap m_Pause;
    private List<IPauseActions> m_PauseActionsCallbackInterfaces = new List<IPauseActions>();
    private readonly InputAction m_Pause_Newaction;
    public struct PauseActions
    {
        private @GameInputControl m_Wrapper;
        public PauseActions(@GameInputControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Pause_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Pause; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseActions set) { return set.Get(); }
        public void AddCallbacks(IPauseActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IPauseActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IPauseActions instance)
        {
            if (m_Wrapper.m_PauseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseActions @Pause => new PauseActions(this);
    public interface IPlayerActions
    {
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnFireballCastByKeyboard(InputAction.CallbackContext context);
        void OnFireballCastByMouse(InputAction.CallbackContext context);
        void OnFireballDirUp(InputAction.CallbackContext context);
        void OnFireballDirDown(InputAction.CallbackContext context);
        void OnFireballDirLeft(InputAction.CallbackContext context);
        void OnFireballDirRight(InputAction.CallbackContext context);
        void OnLegacy(InputAction.CallbackContext context);
        void OnFireballDir(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IUINavigationActions
    {
        void OnNextSelection(InputAction.CallbackContext context);
        void OnPreviousSelection(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
    public interface IPauseActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
